controller_manager_ns: controller_manager
controller_list:
  - name: rrr_arm/rrr_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: rrr_arm/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_joint_1
      - gripper_joint_2
